name: memo_loc
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  uuid: ^4.4.0
  flutter_riverpod: ^2.5.1
  image_picker: ^1.0.8
  location: ^6.0.2
  http: ^1.2.0
  google_maps_flutter: ^2.5.3
  path_provider: ^2.1.3
  path: ^1.8.3
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  